version = 1

# Exclude non-code files from analysis
exclude_patterns = [
  "**/*.properties",
  "**/*.txt",
  "**/*.json",
  "**/*.yaml",
  "**/*.yml",
  "**/*.xml",
  "**/*.md",
  "**/*.log",
  "**/target/**",
  "**/build/**",
  "**/.git/**",
  "**/.idea/**",
  "**/.vscode/**"
]

# Mark test directories
test_patterns = ["**/src/test/java/**"]

[[analyzers]]
  name = "java"
  enabled = true

  [analyzers.meta]
    runtime_version = "8"

[[analyzers]]
  name = "test-coverage"
  enabled = true
