version = 1

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "8"
  # Build tool: maven or gradle (helps analyzer run the right commands)
  build_tool = "maven"

[[analyzers]]
name = "test-coverage"
enabled = true

[[test_patterns]]
  [test_patterns.java]
  patterns = [
    "src/test/**"
  ]

