version = 1
test_patterns = ["**/src/test/java/**"]

[[analyzers]]
  name = "java"
  enabled = true

  [analyzers.meta]
    runtime_version = "8"

[[analyzers]]
  name = "test-coverage"
  enabled = true
